name: Create a sample provenance

on:
  workflow_dispatch:

jobs:
  
  generate-provenance:
    steps:      
              
      - name: Generate provenance
        uses: slsa-framework/github-actions-demo@v0.1
        with:
          artifact_path: <path-to-artifact>

      -
