name: Create a sample provenance

on:
  workflow_dispatch:

jobs:
  
  generate-provenance:
    name: Generate build provenance
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2

      - name: Generate provenance
        uses: slsa-framework/github-actions-demo@v0.1
        with:
          artifact_path: none

      - name: Upload provenance
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: build.provenance
